# 1.5 简单统计应用

## 1. 生成正态分布数据

In [1]:
import numpy as np
mu, sigma = 0.0, 1.0
g = np.random.normal(loc=mu, scale=sigma, size=1000)

In [2]:
g1 = np.random.randn(1000)

In [3]:
g = (g - g.min()) / 10
phy = np.round(((100.1 - 20) * g + 20), 1)
g1 = (g1 - g1.min()) / 10
mat = np.round(((100.1 - 20) * g1 + 20), 1)

## 2. 简单的统计函数

In [4]:
np.mean(phy)

42.1757

In [5]:
np.std(phy)

8.166585547828419

In [6]:
np.min(phy), np.max(phy)

(20.0, 71.7)

In [7]:
np.percentile(phy, 80)

49.0

In [8]:
np.median(phy)

42.1

In [9]:
marks = np.vstack((phy, mat))
marks

array([[44.7, 27.4, 42.9, ..., 38.1, 31.5, 21.5],
       [29.4, 42.3, 52.4, ..., 30.1, 46.6, 49.3]])

In [10]:
np.mean(marks, axis=1) # 沿1轴方向计算平均值，分别得到phy和mat的平均值

array([42.1757, 42.7777])

In [11]:
np.mean(marks, axis=0) # 沿0轴方向计算平均值，得到每个人两个学科的平均值

array([37.05, 34.85, 47.65, 47.75, 41.3 , 58.25, 36.55, 42.2 , 35.25,
       45.1 , 39.15, 52.4 , 34.8 , 35.2 , 49.95, 36.  , 49.2 , 40.65,
       44.85, 30.65, 42.2 , 33.95, 46.2 , 34.25, 32.1 , 38.4 , 45.45,
       49.4 , 39.45, 47.2 , 37.95, 41.05, 37.7 , 43.5 , 37.35, 26.8 ,
       44.15, 50.25, 39.6 , 38.65, 52.4 , 32.7 , 37.55, 47.1 , 39.4 ,
       42.9 , 47.1 , 32.85, 42.85, 39.6 , 40.1 , 52.5 , 40.55, 41.9 ,
       35.9 , 29.3 , 36.3 , 39.3 , 36.2 , 52.6 , 36.15, 42.65, 29.45,
       48.9 , 46.  , 41.5 , 31.5 , 39.2 , 52.55, 47.25, 40.15, 35.9 ,
       43.8 , 43.85, 45.8 , 32.95, 33.9 , 48.35, 41.1 , 46.95, 39.85,
       43.95, 39.65, 39.95, 46.9 , 38.95, 38.5 , 39.25, 39.6 , 54.95,
       36.75, 44.9 , 44.35, 39.45, 36.55, 39.25, 39.6 , 42.95, 47.3 ,
       49.85, 49.8 , 37.85, 39.85, 36.6 , 33.9 , 38.9 , 51.  , 48.85,
       40.6 , 45.2 , 35.5 , 49.05, 37.45, 41.95, 46.35, 33.55, 49.85,
       47.75, 35.85, 44.45, 59.45, 33.7 , 39.95, 51.15, 41.4 , 47.45,
       47.4 , 38.25,

In [12]:
np.std(marks, axis=1)

array([8.16658555, 8.18146397])

In [13]:
phy[phy > np.mean(phy)]

array([44.7, 42.9, 47.4, 50.3, 47.7, 44.2, 45.9, 44.7, 42.5, 58.4, 53.4,
       44.2, 52.1, 46.7, 46.7, 44.8, 64.1, 49.2, 44.2, 46.2, 56.7, 46.8,
       48. , 43.7, 58.9, 42.7, 43. , 65.6, 47.2, 49.7, 46.8, 50.2, 49.3,
       42.6, 47.4, 48.2, 44.6, 49.3, 45. , 45.1, 46.9, 44.3, 42.8, 46.7,
       46.7, 44.3, 46.4, 57.5, 42.8, 42.3, 44.8, 44.7, 52. , 46.6, 42.3,
       48.7, 61.9, 56.1, 49.4, 45.7, 49. , 52.2, 52. , 50.2, 50. , 48.8,
       53.6, 42.2, 50.2, 52.4, 48.8, 43.4, 55.7, 43.1, 50.1, 48.7, 45.3,
       47.4, 48. , 53.3, 45.4, 57.7, 42.4, 49.8, 49.6, 48.1, 49.5, 49.3,
       48. , 60.1, 42.5, 50.7, 49.2, 49. , 49.3, 42.2, 54.4, 50. , 56.3,
       45.3, 43.4, 48.9, 50.3, 42.4, 71.7, 54.2, 60.7, 61.5, 42.8, 45. ,
       46.9, 48.9, 42.4, 51. , 49.8, 43.2, 47.7, 47.8, 49.9, 42.6, 46.3,
       42.6, 50. , 43.6, 43.1, 59.8, 51.2, 58.7, 42.6, 54.2, 46.9, 47.1,
       50.5, 46. , 49.7, 48.1, 43.4, 47.3, 55.8, 44. , 48.3, 42.4, 57.4,
       50.2, 46.9, 55.1, 43.6, 50.7, 45.9, 47.5, 45

In [14]:
np.where(phy > mat, 1, -1)

array([ 1, -1, -1, -1, -1, -1,  1,  1, -1, -1,  1, -1,  1, -1, -1,  1,  1,
        1, -1,  1, -1,  1,  1,  1, -1, -1, -1, -1, -1,  1, -1, -1,  1,  1,
        1, -1, -1, -1, -1, -1,  1, -1,  1,  1, -1, -1, -1, -1, -1,  1,  1,
        1, -1, -1,  1, -1, -1, -1,  1, -1,  1, -1, -1,  1, -1, -1,  1, -1,
        1, -1, -1, -1,  1,  1,  1, -1,  1,  1, -1, -1, -1,  1,  1,  1,  1,
        1,  1, -1, -1, -1,  1, -1,  1,  1,  1, -1, -1,  1, -1, -1,  1,  1,
       -1, -1,  1,  1, -1, -1, -1, -1, -1, -1, -1,  1,  1,  1, -1, -1, -1,
        1,  1,  1, -1,  1,  1, -1, -1,  1, -1, -1,  1, -1,  1,  1,  1,  1,
       -1, -1, -1, -1, -1,  1, -1, -1,  1,  1, -1,  1, -1, -1, -1,  1,  1,
        1,  1, -1, -1, -1, -1, -1,  1,  1, -1,  1, -1, -1, -1, -1, -1, -1,
        1, -1,  1,  1,  1,  1, -1, -1, -1, -1, -1,  1, -1, -1, -1,  1,  1,
        1,  1, -1,  1, -1, -1, -1, -1, -1, -1,  1, -1, -1,  1,  1,  1, -1,
        1,  1, -1, -1,  1, -1,  1, -1, -1, -1,  1, -1,  1, -1,  1,  1, -1,
       -1, -1, -1, -1,  1

In [15]:
np.where(phy > phy.mean())

(array([  0,   2,   3,   5,   7,   9,  10,  11,  12,  16,  22,  27,  29,
         33,  34,  37,  40,  43,  46,  49,  51,  54,  59,  60,  63,  64,
         66,  68,  69,  72,  73,  74,  77,  79,  81,  82,  83,  84,  85,
         86,  89,  90,  91,  92,  94,  97,  98, 100, 106, 109, 111, 113,
        114, 116, 117, 119, 120, 123, 124, 125, 128, 130, 133, 134, 135,
        140, 144, 147, 151, 152, 154, 159, 160, 161, 172, 174, 181, 185,
        186, 190, 192, 197, 198, 200, 201, 202, 204, 205, 208, 210, 212,
        214, 216, 221, 222, 225, 227, 228, 229, 230, 231, 232, 234, 235,
        238, 239, 240, 241, 243, 246, 247, 248, 249, 250, 251, 252, 253,
        255, 257, 258, 259, 261, 262, 264, 265, 269, 270, 271, 272, 273,
        274, 278, 280, 281, 284, 285, 288, 290, 291, 293, 295, 296, 297,
        298, 300, 301, 304, 306, 308, 309, 310, 312, 313, 315, 316, 317,
        320, 321, 322, 325, 327, 328, 329, 333, 336, 337, 338, 339, 342,
        346, 349, 350, 352, 353, 354, 355, 360, 361

In [16]:
grand_a = np.mean(phy) + 20
grand_b = np.mean(phy)
np.select([phy >= grand_a, np.logical_and(phy >= grand_b, phy < grand_a)], ['A', 'B'], default='C')

array(['B', 'C', 'B', 'B', 'C', 'B', 'C', 'B', 'C', 'B', 'B', 'B', 'B',
       'C', 'C', 'C', 'B', 'C', 'C', 'C', 'C', 'C', 'B', 'C', 'C', 'C',
       'C', 'B', 'C', 'B', 'C', 'C', 'C', 'B', 'B', 'C', 'C', 'B', 'C',
       'C', 'A', 'C', 'C', 'B', 'C', 'C', 'B', 'C', 'C', 'B', 'C', 'B',
       'C', 'C', 'B', 'C', 'C', 'C', 'C', 'B', 'B', 'C', 'C', 'B', 'B',
       'C', 'B', 'C', 'A', 'B', 'C', 'C', 'B', 'B', 'B', 'C', 'C', 'B',
       'C', 'B', 'C', 'B', 'B', 'B', 'B', 'B', 'B', 'C', 'C', 'B', 'B',
       'B', 'B', 'C', 'B', 'C', 'C', 'B', 'B', 'C', 'B', 'C', 'C', 'C',
       'C', 'C', 'B', 'C', 'C', 'B', 'C', 'B', 'C', 'B', 'B', 'C', 'B',
       'B', 'C', 'B', 'B', 'C', 'C', 'B', 'B', 'B', 'C', 'C', 'B', 'C',
       'B', 'C', 'C', 'B', 'B', 'B', 'C', 'C', 'C', 'C', 'B', 'C', 'C',
       'C', 'B', 'C', 'C', 'B', 'C', 'C', 'C', 'B', 'B', 'C', 'B', 'C',
       'C', 'C', 'C', 'B', 'B', 'B', 'C', 'C', 'C', 'C', 'C', 'C', 'C',
       'C', 'C', 'C', 'B', 'C', 'B', 'C', 'C', 'C', 'C', 'C', 'C

In [17]:
np.piecewise(phy, [phy > grand_a, np.logical_and(phy >= grand_b, phy < grand_a)], [100, 60])

array([ 60.,   0.,  60.,  60.,   0.,  60.,   0.,  60.,   0.,  60.,  60.,
        60.,  60.,   0.,   0.,   0.,  60.,   0.,   0.,   0.,   0.,   0.,
        60.,   0.,   0.,   0.,   0.,  60.,   0.,  60.,   0.,   0.,   0.,
        60.,  60.,   0.,   0.,  60.,   0.,   0., 100.,   0.,   0.,  60.,
         0.,   0.,  60.,   0.,   0.,  60.,   0.,  60.,   0.,   0.,  60.,
         0.,   0.,   0.,   0.,  60.,  60.,   0.,   0.,  60.,  60.,   0.,
        60.,   0., 100.,  60.,   0.,   0.,  60.,  60.,  60.,   0.,   0.,
        60.,   0.,  60.,   0.,  60.,  60.,  60.,  60.,  60.,  60.,   0.,
         0.,  60.,  60.,  60.,  60.,   0.,  60.,   0.,   0.,  60.,  60.,
         0.,  60.,   0.,   0.,   0.,   0.,   0.,  60.,   0.,   0.,  60.,
         0.,  60.,   0.,  60.,  60.,   0.,  60.,  60.,   0.,  60.,  60.,
         0.,   0.,  60.,  60.,  60.,   0.,   0.,  60.,   0.,  60.,   0.,
         0.,  60.,  60.,  60.,   0.,   0.,   0.,   0.,  60.,   0.,   0.,
         0.,  60.,   0.,   0.,  60.,   0.,   0.,   